version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_BASE_API=http://app:3010
    depends_on:
      - app

  app:
    build: ./backend
    ports:
      - "3010:3010"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./backend/init-db.js:/docker-entrypoint-initdb.d/init-db.js

volumes:
  mongodb-data:
